import { readFileSync, existsSync } from 'node:fs';

export const root = new URL('../', import.meta.url);
export const read = (path) => readFileSync(new URL(path, root), 'utf8');
export const json = (path) => JSON.parse(read(path));
export const site = json('content/generated/site.json');
export const home = json('content/generated/home.json');
export const pages = json('content/generated/pages.json').filter((page) => page.enabled);
export const blueprint = json('scripts/launch-blueprint.json');
export const host = 'https://build-the-pyramid.github.io';
export const draft = process.argv.includes('--draft');
export const forbidden = /\b(?:Yorich|starter|placeholder|skeleton|Riftfall Survival|Fact Pack|Evidence ID|Generated by|Codex|Claude|ChatGPT|localhost|automation platform|internal prompt)\b|Replace this|template preview|example\.github\.io|waiting to be added|could not verify|insufficient evidence/i;
export const errors = [];
export function check(condition, message) { if (!condition) errors.push(message); }
export function finish(label) {
  if (errors.length) { console.error(`${label} failed:\n${errors.map((error) => `- ${error}`).join('\n')}`); process.exit(1); }
  console.log(`${label} passed.`);
}
export function validate() {
  const all = [home, ...pages];
  const slugs = all.map((page) => page.slug);
  check(new Set(slugs).size === slugs.length, 'Duplicate enabled slugs');
  check(JSON.stringify([...slugs].sort()) === JSON.stringify(Object.keys(blueprint).sort()), 'Launch URLs must exactly match the eight-page blueprint');
  check(!slugs.includes('wiki'), 'Unexpected wiki route');
  check(site.hosting.siteUrl === host && site.hosting.basePath === '' && site.hosting.customDomain === null, 'Invalid production hosting configuration');
  check(draft || site.readyForLaunch === true, 'readyForLaunch must be true for production');
  check(site.theme.appearanceMode === 'legacy-v18' && !site.theme.templateVersion, 'Complete React renderer must be selected');
  check(!forbidden.test(JSON.stringify(site)), 'Forbidden public site copy');
  for (const page of all) {
    const label = page.slug || 'home';
    check(page.title === blueprint[page.slug]?.title, `${label}: title differs from blueprint`);
    check(page.description === blueprint[page.slug]?.description, `${label}: description differs from blueprint`);
    check(page.title?.length <= 60, `${label}: title exceeds 60 characters`);
    check(page.description?.length <= 160, `${label}: description exceeds 160 characters`);
    check(Boolean(page.primaryKeyword?.trim()), `${label}: missing primary keyword`);
    check(Boolean(page.hero?.heading?.trim() && page.hero?.lead?.trim()), `${label}: missing hero/H1`);
    check(page.factsStatus === 'verified', `${label}: unfinished factual content`);
    check(page.lastReviewed === '2026-10-01', `${label}: unexpected review date`);
    check(page.sections?.length > 0 && page.faq?.length > 0, `${label}: missing sections or FAQ`);
    check(!forbidden.test(JSON.stringify(page)), `${label}: forbidden public content`);
    check(!/\/Users\/|\/private\/|[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(JSON.stringify(page)), `${label}: private path or email in content`);
    check(new Set(page.sections.map((section) => section.id)).size === page.sections.length, `${label}: duplicate section IDs`);
    for (const section of page.sections) {
      check(Boolean(section.id && section.heading), `${label}: section missing ID or heading`);
      check(Boolean(section.intro || section.paragraphs?.length || section.subsections?.length || section.steps?.length || section.table || section.links?.length || section.externalLinks?.length), `${label}: empty section ${section.id}`);
      for (const table of [section.table, ...(section.subsections ?? []).map((sub) => sub.table)].filter(Boolean)) check(table.rows.length && table.rows.every((row) => row.length === table.columns.length), `${label}: invalid table in ${section.id}`);
      for (const link of section.links ?? []) check(slugs.includes(link.slug), `${label}: broken internal link ${link.slug}`);
      for (const link of section.externalLinks ?? []) check(/^https:\/\//.test(link.url) && site.allowedExternalDomains.includes(new URL(link.url).hostname), `${label}: unapproved external destination ${link.url}`);
    }
    if (page.slug) {
      check(page.navVisible, `${label}: no navigation access`);
      check(page.relatedSlugs?.length >= 2 && page.relatedSlugs.every((slug) => slugs.includes(slug)), `${label}: missing or invalid related guides`);
    }
  }
  const start = home.sections.find((section) => section.id === 'start-here');
  check(pages.every((page) => start?.links?.some((link) => link.slug === page.slug)), 'Homepage must link to all seven guides');
  const pkg = json('package.json');
  for (const name of ['typecheck', 'lint', 'validate', 'build', 'build:site', 'audit:seo']) check(Boolean(pkg.scripts[name]), `Missing npm script: ${name}`);
  for (const [, name] of read('.github/workflows/deploy.yml').matchAll(/npm run ([\w:-]+)/g)) check(Boolean(pkg.scripts[name]), `Deployment uses undefined script ${name}`);
  check(!read('.env.example').includes('PIRSCH'), 'Unused analytics variable');
  check(read('.github/workflows/deploy.yml').includes('NEXT_PUBLIC_GA_MEASUREMENT_ID'), 'GA workflow variable missing');
  for (const asset of Object.values(site.assets)) check(existsSync(new URL(`public${asset}`, root)), `Missing asset ${asset}`);
}
if (new URL(process.argv[1], 'file:').href === import.meta.url) { validate(); finish('Content validation'); }
